### ISSUE TITLE
WinWorld Classic External Resources

### ISSUE THREAD

**Issue by Commenter25** [CocoTheMii/winworld-classic#1]
Hello! Your userstyle [WinWorld Classic](https://userstyles.world/style/512/winworld-classic) references multiple external resources. The fonts seem to be completely broken, due to WinWorld's cross-origin security policy. I'm unsure if there is a way to fix this, but it may be worth looking into or simply removing for code simplicity.

The images work, however, I would recommend using Data URLs. This would remove reliance on an image host, improve privacy by removing connections to said image host, and improve speed by having the file always local. 

You can make them using [online tools](https://ezgif.com/image-to-datauri), ideally after compressing it with a tool like PNGGauntlet or Trimage; but to save you some effort (and since I can't make a PR directly), I did this already. My preferred way to do this is to save them as a variable at the end of the file (for readability), then refer to it with `var(--name)`.

<details><summary>Variable code</summary>
<pre><code>
@-moz-document url-prefix("https://winworldpc.com") {
    :root {
        --stars: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAgAAAAB9CAAAAADxMIQQAAAFJElEQVR42u2dO28TQRDH7yKQC3SCSO4uQjrRWAjkykWEK1K5c5cqBQqdJSQalI6KjoKCJp27qyI+Q7p8Cz4HHYIAso+zvbc7u/PY/6+gCDr7Zl/z8MxsURzkut75X1eFFgKFqMK+3ffxMwlD9/5uXqhniBAjou+suIVeFhOSzzkfpXvnOtYHkwkxKwBgZ4EhADIY+z44vTUgRFKbQtdXAwGrufmE4QAAACEWwYRLpPkE05r3mv4T7ZzDfRQFfaQ3IPrYWBjRxu5iWRZ5HuNLnBO02+NO45tPMXnCIf69cNVZub0/ET04liBEg8lno9z4NwcSx3VHJ2HP1zcSxuyE6pOYtBBjXLd6F7jBaiex/P2isiyfHMcW4h+fVRwSlOkU8y8vZJ9m5RGzEHGtKman7/Xl7Y9vl6e6laYJIbzWhuPq2XPgPj+9/v71VTP0E2UhSAjK/MBEcd2nHx5zT+BMnhBTnavGJ+b86I3/97VSzoAQISKtSaleX5ej8qF+bRlXCN4Z0hvX3RRiSjUSQCUrDMHf0+QEY5A1dBErSSD9xN23VxuxAgT+m/aIVZSCvtQZMIRCtEOdxW7Eyuqc6hXiY+xX7USstjzM8LguCFbRsb+ALGJVYbI0MihiRb/VhWaLjywIYZR6/Hbb2RtswKz7/+yeATMVIETGXHQ36lCTnVKrNlxC2GDXrwpxi+ZnFoTwYML2cBKidA0TX9nYmK9bcPctYuy48VViIYayimazS/Htz++ErTPBQgBRs+7nHmThyN1g7e0izdAsQvbFQtumAsNoZ1wPH7A81KytM2wQ8b47j7OLVq8A6DmtARDNuv/P41zHIzvzao498ItIkZO0zq6XEBFMyqBypsMPm9mjrT5zPijPlShJtoUXBEKQ1OVfqhCIM8H8BR2QbXfPiO1hwEZQpze913+UmHkGl7rOY4wkdy/BOc3nKSsiKM8V138YsAtCOr3h+o9kx5ELV/G8Q3LXcrMWCrgxOOVftBFwYdxTJsDpqgKilk5B5UxqaqEsOrs2Wzrda4koKdG0FWM1jxCbdriOlk4V8eiSdPlPs4yjCtFt6ST20CWvhRqknwP1ZDRnN9zIENjSyaCeFO3sCuikLp/DerKK4+wmgLwJuT0cWh+KTk7a+257f4votQiCOr0RtIlz22WUXf6J9ORwZ7fF5hu0mKEnWdDdNcKtI0oqPVnFFMKwjR7wrFOX/2S/2Xs6u7lfVYB+KWAXCwjh5fZi5bhj4kYq0Id3TpeknujLAklXwBQ7a6HkBuPQNQIAlYwgxCayskKDWff/WVdOV7AQGQcRaZzd2oIQeTKDEBYx0eU/z6sKiIjZ5T9ZTpfgqwpsU0EIzDqEAP045HRhGoB+wj3boHImXP8hGqerp5U6HAj8usytSK8JwPQEGYBIRgLorp7maftAcihx53SlFKLfiJBjxRF1MAFabQgRHUzotzqDsysxMc2hpGOrMhsxgtxwqMy2rDqg//wrs000v2IXQkDDZt/K7G5TDxltcGplQjiq3JhtH/ZUZo9jqA4T+k8bexLb9lbejSKoDhP6jxsJDgd3Uw+Sy5zQmcQfE82vUglhMF/URNF27pXnHE2ykB8IgDZyb5JFwZZDpe2+rv+bZJmwafLq7GHiHl8QBdOJhUvML9Bcow+Hg8BoaWoMCZP+qCBE1oR0+ReTnNSiRwQPJm6k+g06nZKDa7dTscYQ5A2aZCXhpdg3U20AKXv5Z+m+SnoNYB6XOdFGK4Z5TZ7lgz8BlmK9qpN6nSgAAAAASUVORK5CYII=)
        --logo: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAANgAAAAtCAMAAAD7oVV1AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAL3UExURUdwTMB9F7t1EtKcKNKcKLpyEb56FbpyEL14FNKcKMSEG9KbKNKaJ7p0Ebt0EdKaKNOcKLlxEMODGseJHtGaJ7t1ErhwELlwELt1ErhxENCXJblxEMKAGNKbJ7lxELlxENOcKMyRItGZJsaGHLhwELt1Erx2EtGZJrx3E7lwEMaIHLlxENOcKLlyELlxENKcKLt0EdOcKM+VJNCZJtOcKNKcKL97FblxELt1EtGYJrlxENKcKMF+F798FsyRItKbJ8+WJdKcKNGZJrhxELlwENGaJtKcJ82TIr97FtGZJs2TI86UJM2SIsKBGdKcKNKbJ7hwELlxELlxENKbKLlxELlyELlxELlxENKbJ7lxENOcKL55Fbx2ErlxEMuPIdGaJ714E8qOILpyELx3E8+XJc2TIsSDGtGYJr56FL56FdCXJcuQIcJ/GMSFG8qNILlxD9KcKNKbJ755FLhwENKbJ9KcKNOcKLhwENGaJ7lyEbx2EsB9F8SDGs+XJb56FdCXJb56Fc+WJLpzEcySIrp0Ec2SIrlxEM+XJdCYJr98Fs2SI9OcKL97FblxELhwD8mLHr97Fbx2E7x3E8yRIsF+F796FblxEMOCGcOCGcmNIM6TI796FcySItKdKMKBGciLH7hxEM2UJM2TI8KCGc6VI756FcyRIsSEGsKCGdCYJciJHtCZJrx2E8B8F8F/F8eJHb98Fr54FMmMH757Fr14FciLH9GaJ9OdKceIHsSFG82SI758FsOCGsaHHMGBGcaHHLx2E8KCGdOdKdKcKNGaJ9KbKMaIHcSFG8ySI9GZJ8qNIMyRIsF/GL14FNCYJr56FdGbJ86VJM2VJMKBGcOCGtCXJtOcKc+WJcqOIL98FsmMH7pzEbt1EsaGHM2TI7lyELx3E9CZJsiLHsuPIceJHcSEG8WFG8SDGsiKHrx2EsB9F9OeKcuQIdKdKNKaJ82SIrt0Eb55FdGbKMF+F7hxEMySIs+VJM6WJLlzEcB8FtGYJ9KbJ9GcKOgcKlUAAADCdFJOUwACuWbKXQY1/ZkENQ8mF6bwpwESphC6PMq5I0kIYo1z9WYuZmQiLoL1hQzNHBuK+k/qwxTTtmawRSbwq9/Ka0dmwqas5zxwpNF2tOBh+VBA1txS5ZNu0caReYmV/b+Q9TxK/ejMUVj6cHvxn/Eo07xFWMNZVF7Ho3pg2ebw75rbu+mgQ+Jx9dP8qvuiNZ2XloZWrOz17fg9yB+r+T7eXly1l4qX9Y3Np4zkdO12sR6Do4MujV73nNC46L7q1duRUve9R+T76QAACSpJREFUaN7tmWd4E0cax8eYE3cYi8g2JgYXurEBU0PvvZfQSQgtlFBDEkKO5AgQSuACJCQkXMrd5ZJLvUsuucv1ukWWtFrZslZa9S5ZknvFhny4WZX1rmTZWj1Pki+eT6OZnf/M79133ndmBUBP6Sk9pad8T6W44PpPf8DpU0R9U3JT4naKUnJFyQmLFjXb2rb/cGADF0kk00bE6Rx3WiJZtDlU7yvIXAAU2OpJg+GVLh8TqimkjLCZ/PZbcTpH2Uxme69QfaQkOydnJ9+5BmfnZGc/zGt6Ojs758S0AQDsrDdQbt9nXXurQE0h5UemMiX1QZzO9MtkE/Vx2LV+DSHJMzy7SRjwp3hDxtjgU8vhU9dJSt/aur/r2QVqCgKza5zV78cDG90kdS2LmNIeoEqptzjdA2aaDRrPC5mcppE2f4Dy/pIZe9vdii7oxtkEagoCa7DUyX8SF4yqVi0M/8jd51XIiMe4yzKVleplxK84Tdvr2y2u14uDg2+u3FHczexCNYWAlUnVaHywypb7/SO/HrHI5NgqzjvIN2uMdKN8GWeDr/drXKwpEijfhSYLVtEVGFHLgu2uJPAq+Utsb8YG0tOCVSE/y+REG8ZOzyQ+/XehKRgsY7ZRheBHOjJFm8GtRqsQbA/bVFTfZFRtzO0yxPflRoEkNXNzuwglIlFcMJiXOwEDf7SoUd15doois1KhRZAqlN0jKRvsVDUWUhtXkl+SH86BbF1cMG3LljHTCtKT0wzFks3Xt264OCanaEIGN23ll5Tkj2NMk79+e+dgg0tOrF8PJxfHgI2iCAyRsxF8jN0DfyOI7kXW3jZGbV64bjKbL4KO+j4YBhYzWZMkydFfJaXJmGbTTCYfkA0NpP0MJwNusdWbzbuB6EZzc/0jnYEN3toMJ2fG7SsA4v/ywMByoxZBI/s6fa9Bqp44Ea7C8W64aZO/SaF6LxQK+uwlA5o7oKP+P3DWVG83KD2l3lJKeTUZTQAeXtwMDzSaSo/F4qU0hlts1s7xGzSaL1IeNJnIwCedgBU12/wNTRQcV0oFnsi8zQd7wmLF2X1dYFYatTuWQr+p/U3YgxfbKwn5tjDMo01S/Uec+srPNAaDRqonrNa6aqP31SQ0wQi4vHbKrSfqKiqshN5HzYkEmV5lHuO1rz82kIZK580YsIzTNhOptDirZVarlTB6r862cMEyRmpcckS+OvRrJwl9P22sHEN1j4dappsMMCkvicBQ1dreHXXVrjqf9183L63YtvE+jmmtvl8I15zebCI17uor7+edXDFrF+agCd+dCFjA2XpwksKjkRKfPhcDVmSrh8B1jz/3zMmlD8m1hE/qtOKcNwbmOGkdujIUEN4ss1RMzACr1HL05RnBptN+uPOnhLd0nx+Xysp7c+qI6tqloEf124brdHjFl4I1Byxua6CMh/NCv2ZkYTimNn4SBlPqHQgmMx4fOmxy32iwgc1mg9dFp4Z+rftUpSZkNA/sEOM3h8VBrzAFnPQsAI7o7+L4pdBpiPTUYYUgHtj4SLrKWOnAa8r/Llhzk82uMZ5PY1dTqEVracWxMJjCUVOufbu4szx2Ah5nXAfXRboGndeqVBiaxQETr2H8Zi5TXeSnXPI8AA64CQydFNzY0GtoNC0uWCEr85JLiyOfFwvUFL9pbnLS8zjLWakt/5Z+LAKmQpBnO03Q6TZSo1Cd6ujbU6fCEYQLBs75aDQ4ZeZM0mIdPwja9AWFVneQ2TASs0Z/j5WOARsytuOk+zdCjuzKFKj5dFuZxfoQdzWDvqHx8lWiDrBhnYKNqIexdgF34F+tGFLFAztUCv3mZTj3BFO7kw6u+/dSNd4IN7/4coO3BV8aF+wv3L3qVn/7QD+Bmjdg8r7HP1rdcTkQbRoLtqDzI9UNv0YvT+WOO+Brxflg4qP6e0j5CgAuQFOqguFnaiWB6d6GdmkzOFvRGXHBnuWCeWSNLFiimtPI0pZdM3hgX0krdLX7WbAVnYMtIr3WxjTeWXFNtYPviuCqj65BYSi+SJbWYcE3P3KNXqU73A/0ssNDeIfNYsB6c1Qe1LgwFixBzYwxZdK7QwbxVvM7mCvQPBbsyc7BJAZ31MBxt510TX+e1J/g3Mi9zGMN7e67U0LngTm+uwi2JOUdA7RLaoJgSr28AywxzYyt7UZtNFjAqGLBHNwtxgNrd0YNHDnaYkX5YAOOQsugc4crYZzZET47wD2CFu7RaHz0+LHJgCWoeQu+lPHDeKvZZPDR+Fo23KfFAQsYtVGu+KhHhvPBwB/gtUJ35bhXSmDhNz8K+oPuxeMWS7WcE7MEgCWomQ/BdHm8xWxhwIZFwNA4YCUQTDef93nI7mmpjQKb4CEaEUedwnV3Y/iLY8pyeHbArAq9uvZUcmCJaU5g1jeJu5Y+MKFrQ87bFdhrMQNzyNg3JpoN/QbXVqgd7NH5txY1jqrUatWQycmBJaZZ/A+nFpEP5chsNSv1qkLQHZj4HR+tCx0BwiYKXsr7R3+mgDmmBscw/GSkZbqmWo6isGUWSA4sQc1Dlgodfu0/rDkkNtJD7BrbLRg4C+XxawfYK95lU8BII9Fg05mrIVJT8wBrStHz8FXDFt3aZMES0xT9E560tMZ/p4dvjja/0tmaCroHG7eGqNVpFR98EQxVBXvbyrxEdB4DoO9sZkoE4QSKs9IKePZCuEsVBpag5rFvaBRXu984d+GCZEtzm71JKot8veoSDBxwqnSNat/Rc0UFEnhVbaAU2qiTB1NehS8WTsmJT69VBu/zPwfJgiWoCd56XYXLrU7KQNpJ0kC5W9jursHAl9UYggUH+u1kwHNkFY7Egu0O+g0nZQHxG8wXGGRe8mCJaQLw9SQHiqldPm9lpdetV3dcGLoBA6s/rNVhFS53KUV5nXMzP8fRGFcE4Hm486qmcFuegkGmagjve/ZAEsJMjK0Hyz4Ihk4WrMmUuVew+3La2tJi/XAhJ1ufYcCWcJ7bzIBxXPvYsoMo7qDrCNlH+8EgmnagC2LAXhk+PzWVl8lHDR+amrqO95B4KmxbG1sPxdupQ1NPiQRrhsqTK7JmZS3clsc7Dw+eOnR+KtdU6VOhIpcUDFv651lZWYWMD2Suhk+v6/lztqf0lJ7SU6LK/wGw7wp3qYMGGgAAAABJRU5ErkJggg==)
        --magestic: url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAMAAAD04JH5AAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAL3UExURUdwTPSEKvZcJvZsJfRYJvdoJ/FKI+LHpL6JQPVrJl24N/VkJr/PJPVpI/FJI/JPJPJUIvFHJDCHbvReJJ/IKvNfIvRsIvRkJPVvIvA2Ju6/Ify+HfJRJPaDIPNkIvFLI/FHJPJVJPA0JoPDNhikRyKEaPmaHvFEIwqSWvV8IPNdI/RuIiN9bvuqHvA2JIzEMUKwP/mSIPmgHfZ7IfyzHPqqHPJeI/RrI8TLJ+8mJe8qJEQ/mEM8mPR0IfbKHfV5IQebTgt8aAeYUQ5wcfiNH0GxO5/IKxZrevuxHRNvd2q7Ne8lJanLKjA/kyl4hu8mJO4lI1RCm+LTH4LBMfeJHyytRPu4G4bCMWE5lkCwNP/RGPHaG+naHLbOJzA3lQSRT/mmHP3IGtv/ShBOg/yzHP/aGPvbGf3BGmy8NjyxR8zSIvy2G00mjP////JdIv7QGPV7IPWAIP7MGPiaHfJYIvqqHPy+GveSHvuyG/y6GvzCGf3GGfR2IPNhIvmgHPNlIvRyIf/aFwGdT/7dF/u3Gvu1G/3JGTWuQPFPI/qtG/aDH/qnHPePHhFvdAaOW//XF//UGBNpeQWTV/qvGwOhS/iXHQt+Z/TcGfidHfaGH5XFLT+xPvNsIejZHAqkSfmiHCVAmgmGYUmzPKvKKPrdGLPMJ/mkHBpTi9/XHhZggVC1O/aKHhhZhR1MkPJTIo3DLgKZUTBAmvRvIdnVH9LUIAqCZA16aw52bvNpImO5N8vSIiOpQiysQsTQIxF0cfiUHna+M/aJHwOWVPy8Gmm6NgeKXqTJKrrOJR2pRvFFIx5EloDAMVe2ORNjfIbBMPeMHm+8NDw+me7aGxKmR3u/MhmnRPP3+Pr8/JvHK/AzI+8mJEhBmvA9I+b07MzH4d3a7MbX4XRaqLDWzY+6vpiayNnu5pPVobe6247Ms1ehmk+7f4t6uerr9Mfn0lhMoEGLkbKo0bPfq0xoqHLJhjpcoGV8ti6XenLBoS2saXagtorMdSOWcGC9XBDM9NkAAABtdFJOUwAJIDMpDv4BBBT+Gf5M3ITraxFA/tDhY1s4I1B4pPTCrJZTG4o3xvJs67u0Ij+ackx88XOmuqSMOcHeUaj5bMPp4MG163HgXImM33uRhPyn8eOT8NnSzbP+vOS85rnc1+DEY9vm0sjunuvQ3OOaYHZTAAAQk0lEQVR42uyYZ1BUaRaGmyZ0I6EBJSnZgKIyqKtTCo6OYd1ZR2etnZnV2i1nt3b/TNV2CzMYEJGsJIUZRGEIioIJJYNIUNEmtCAgQoOSg4ogYE6zP/ac74buZhRv0z+2topjKbeh5Tz3fd/vfN9tHm+yJmuyJmuyJuv/unR1rEQO9jb6/6v2lvPtJBKJvY5Gv0VLrXcL2SuBtqOFv7+fn5+LgUAjgI3W1tzfrL1EhwIW6CxZtTI3KSmpyEJHQx2FrstdN/I5vlln3solKIJQe9U+rICAlVaERyME669W/Gm5qYEBFwAvL69FPJ6+bYQXKU9PTyNLSysjbW0j+Eco1J9YHAXWrvfu3Vtu6vTR/76uvDyj3GDRuoyMjPLy8oSEiAiveVD7AnJz7Sws7OzMl9mITHV4QnUVEehar7h7966zvcPU8UKpPydqN9ScdbtJRUXV1wMFQHh5ghu5SUWQSYnExMTEwcnaQF0ErY0r2tvbZc56oqnaH3iL9tK4uB+VKi7uKqHISEhAM2gEicTbOzMszEFkra4RBg7OMj29sExvc0eYLL8RUWvhnPj4/fuP07UfKj6eooiqBx1QBkDwJwhAoGdszxeqieDkEJaZ6e0tkdhZrLLiq4qoNePvx09HRkbuZAquI08DB0IAQ0Z5AlGB8gFF0JM5i9TLpIBnYGQO7f38i5IC9q20XWKkyINwUeTO8PDw2Ng9bMXGhocDB0DEgw5EBi/WB2KDnkzNIQmy69rY+fsn5Qbs8/SKSFg3x3ahUIuEdGk4tA4NCQnxYSokJDQkFDDCGQZEiCAIRawNsgmMaf4yC6p9RtTuuB/jF/9hoTZv+r+guY/PjV27du1lCq5v3PAJCQ2lGCiEjAREgCSwBA46XO5b5aXAyNYzIqG8HtvvPw3Kf/u7b7H53r2+vr4HoH6Awq++vsiBUuyhEa7upkVIKsIgZIY5O8tE6gKg4VZf10ddpdvjvUN36A19d0DFQO2IwSvk8AUpQIc9sQQh7iqI4EVnUWLi4igSOQnVBwAfFi0m7WP3hFLdsXdMTHR0oKKiowEEIYDhhg9BOE5EQBsCcs1F2rq8ie4TAp7QYOliaE/d/AHsDr2Dg9PS0o5RBVdpwcGBCEEhECNQBMoGCyt1sv/eXXLGUrh7MB5uHrpD82ONyclnz57Nw4KvyY2NxygGkIEgQBxBBMgiEHxt+6m2pvu0/mf/wJsn3aE5tM4vLi4uowqu8vOQAiACoykVwIdwYgMJQoCFOW3CRyX4kEuC6Z+R9mnHkrF5mWFVenr6KargqsqwDCGSASGaGIEioA0MQa7//KlCDUyAHwin/zUtrTEZu1dB68pprb8w1TqtEjCqkCG5EVQABCJCLE0Q4QVrwd/PUUcTAKwZf8vLx+6Vrb9kZdXV1DSRqqmpq8sCispT6YZl+aAC5YMSQTlNYG6pIQBvOiiP3etqrl1rkEqll7Gk0oaGa001ADENZaAQYnaADRAEhgBmYpG/ROKoIQDvy2mt2L1BenlK7fnz509CwZfa2imXpQ3XarJAhnTD4jyIArEBxhKtAU6k3CKYiOZCDdfDJ39uapBC85MnExMPMpWYCBy1l6XXaupQBRABkhBNCNAFnAcYRNwWvE10NZJAoOX2R7jlxNISrOrq6mb4W1JSWooQtVOkqAItgoIA5wEJItmcjfkanZsF688/HX7w/PnzweojKfAHKiUl5U5zdQkwnDxPEFpPVSFBIE0QHsnGAAEyHfiahGD9N09bxFgd94cHg7KxgoKCkKKZINRebmgCgvSyvGR0AdYCzAOIAWMCbM1hjgYTJhC6fU/3J3V/8M3PUNevI8WRlDvVgIAi1IENSBCIBDdYE+gcZoaJJgogdEt8IFap4YFfKw4fPgwQwAAIJaUgghJBDMwDNOE4tRKoHIYZW06QYP1Bun9H731WhYFfUysqKggDIDSXHgQbCEFxXmNaIMYATVCVwFhrQvvyrGa6v/x1xSOWoO/o0YKC1FREoEQAG5AAkni2MZg1QUkCOCWLJqIA079lIDW14FUv3b/j0aXCwkJkAAQUgSFoPWWYD4uRmAA7435aAn/qfDYRCWavGYTblg+8Kjh6tPAKAyDvfXToyqVLhaADItAEtdKmrGkYg2AwAVYCIwHOAgTQs9GdwJY8e/UbUP/Vq9FHUH2MBS3ylr5RYCikCK4TAkhiTVYlmAAS7CASYApgFtAx1DO2Vj8DZmuuv5bLe3s75Ni2W2U19P1EISgIpjRADMAEKoeQAjIL2BjKbNROgdt3Pw+LP1i9mw8dogmyg2AtQAzQBJQgmpWA8oAA6Kn7mGI297vBDvE41bcZRGAJqsGEhhpGAlwIOJBJDGkPTEzVUUBgNivl9X3xuPX2FkNwPRtNgJVASxBDZgHGEObxvFw7AqDnoM79z1zzZkA+fn9x9yhFkFoBMUipLk2kJMhrVPVgFc/S3ARDIBNwVABeuK1+0yv+WMn7bgHBpcKCVDCBkqCJLASMIeVBXFS5lyesP6tl+MTO52z/rObx7WckuHAOCYgJQUeqyUJoTS87eyyQeBBLh8BWHx68rUz0ZKZCbimYve3gAzGXkp+5cA5NoCWAhSBlPaBDsLseUmiFv1zHXuaqzwVA6LbtP8MtnADEZ5QlwIUAMaysoteBDwDEYwr3WRjhr+c7jLsQGQA4gb0b5tZeLH+GBLQEQUeaS9EDsg4wBLAp05Mgdz4ZwzoiIw7+f9n0roNjf3HXs4tnLhAJYCEQD2AdsCFQpDDA7lNyg0Ltjyow/fd1T8ft2aK8NjtfXGRSUIHDqIQKQRmEAAFCyI6IAEV2fC67P9Zfmp6OK0Dnky4FzMObFxUeQAhgIUqbqBQqLQNyJnDh/IT0yZR3D8Zh6Nz6RCkCN28SD3AY0QuRTIL8ZGoZMOsQj6Yff1Cl9mQBz21byfMPx26oR6FA/4kTN9kQYAoVywBnoSqAC/fPqxZ8/8Ep0NmztZN98fAFBXCOBWiGUUSvQwKwZ6cCwNuUK4Bg5jcfUKBraOvQYzYAnc9ycsYClKoC4KmI3g8l3vacDyTCWdXvyUBL15Oenk52QMkfjuT8FuDg+wGIAt7LOHsw887gbyfhw56e/i7m2539I7dv384Za4HSKKRCqGxBprE+VwDe3NVjtuKuobbbQ50KKUba2tpYADqE9CyGVWCYD5uB6jIkZyIbzgCCWdkDCg0eP3yZ09b/mH01tMXDg/SnAM7hMiygAWBDVpoDikFEPZzocwWA/RhOo/QNd7988fIJI0jLk55/e7gv2EIDKAYR2Y3GTEJmFDOnQtlU7h+WCOcefoVbUvfbF2eesd539Y9s3eIu5G1SEoCKQAG7F8CBoJjsBXgiYTYjAqAnc+VzJ+At+Lygr2/0p3NvmdP4487+nhEPdxhY7lvabjMCEAdIBrOVdkNmOz4dT55NcqlTqczYSY1nAoFw7dEro91sGLuHRrZvmm2G5xWmPyOAIgJKi+DAXvpUyjydAYDMVZ0PrASCLwqvdLAxPLHdw92M5MODtGf631I4UKJ0IvphzFZg4gIA7cZqfmK24crm++LH3f0vX+R4bDCjfizYRNpT/ZWOZDgH2QgEqx4HIAIm2gjgzFcPgDf7882jm/+5dpP7AnYvc99OtYf+lADUuTybbMaqJ7JwJgIAYM4zBoC7Tup9XCXgbVj7xQZiPPu84kG6n7jJ9MdjOXkyQQEUZ9IDu1Qj4KJl6gwAIl1Oe7LSvmA2Rhf3E2x7tj9ZAiDASebJiDqQKUXAz9tRV9e+vf3uV3yeZiX4b/vW/tN2FcVvX/u2qwVK1xYoZePVFVpWgUILyXhuDNgMhD2IbIs63SNbglvGRBxGoktkPOYjcbiwSNRsOFFmlE3dBiJDB4myRfdLG/8Y7zn33m+Jtg34LSNRz0/f77e3Pfd77rnnnvM5n4JyUE9fH/XLhZFsAJYMRAojFgeTVSSbTqAifZVu+Fd55kuUcVAv67/E6vPPlxuAIxRyeZ5MiCkpFKrMUfb+qS+Oj1PtQr1cnuMCbBTF8TuiOGYHARbH2VAXrGQC8S3Q9AXKDVAfASi+YpXp/GOBkABcilXJ0D4nWwEozVXmUKhVmQW89TdQfmXqa+vd7uci8MQs1IXfMAMwuLZ7h8nIwuBWWHtLKBTOIUpMsOs9LsPDMzO19bu83jpZPwI0NAZwD4BzgLqgVqrGZKQf4oi6NRxOV2KA1KZhlJkZavz6fDrZOsCHQD86wM8yTsgN8HBAR+yATkwmGeloQ2U4rCUKTOCt/Rbl9u3LtfkwLg+ByoV71AFPtN8ErPY3AOloDAAPgDCsJRrb611d/dmQixgqwpVKLKDPv8zk1q0mL0zTjSjlAtjfR3ybrk1PIVYMHnjxOsKU1Rqi8sAKYE5uaAlXqJVYoO5jJrXuVAYigvkRJfWpiK9hGh0AFwCyUTgGPFRfgJ7ELB1Ut4RbFHF+ai6B/FTjZgapY3D9J798fyKV6IMnpzhAh6cAXQAahT10XBpkg2h5dUWreWVHUHR5umZubu79uTk3B5LlbkF7Lr0NnvyMd0wi/YpemIAFUFLGwwm3KooCeW+icP35+0W/pDmIfdaDcs+I7oCSRjgFtgeAADbZv4FlQtrwbiX9bOL+/SMqeaKThOo3zs/u9eE3DMfkntXg2IcmNQLlkAZDJsI23+5KRcy/3Lx7d+8u7Bd3o7xtd3MP3yNHQT864FiJhpiwdQqtIlPKYhK2jKSKFcbhGNh56rOjo2+PeoUB6Mtj47JBWKxD7hq6iiRiL6CnkBU2nT1lMROHWHIUtTAlPXROd4qb5kezj7F1m8s/L+oQ+suK6IDi7fQYTgaN5g1bGTalXfkCRDfB3kfzzblyO3UJurafPjgixr4g9Psz4DYAneNSuDIvblk1mSPq2NyGpSWfwBDasXX+YPpwBv+0EXvnF8+VFDMLBfq+e8MKoJhk/sOyenNHncDhTQ1Bfh1soNqfujM1VSXa/OdfAxLHORefkNEDvXu40m3btvroF2MC1/ZwL5KOTDP6xEH+IHj8lR4afwZLHIL7B2kQhj39FiNJkAXa7vAdR3RtjEAywvUFD+DrD46ViG9aoBZhTvfPWKdSlC561SGxAoZDI0ihOcaGFZX1MBbP2WLxvXKahSQr2XVSNGbPiEyreAuZTC87GNnlwIVXyxx+INCIt9VbaRqolHD7N9EdFdNyvIs0qg7k2mWcOtXoyCCusx90O3ndI9mzOrsylYWdaA+rRPOzDQlt56tARdVLfgd9XrTvh6EdAgzXlXd2bVbGZIq/cfzIpDtOI57O4WAvWto9NCEMQCyYh0trN4G2+/d7ei74qWq9io00OieuFAgDqAq7JrMV0p3jisGPbMrG5WyfHwfOOIVO82R/tmIlUpwXMPqBT/r88gDjPHO6QFynT/YngvIfewKSrmzw+tiYa9kjTcHpXpHvGlKSEvKXg3hL6AJOcdqyEZ7ePnHiGKxJ9oQsdNwJAKs6I3Kf1ve1YDDaN2fqyZqLa+jhRHWkxNDasuxcq8EY13sSJc4rAwPFkU3hsaWJEKVPoPY4P1VKM+5SOUIHrCbyZEWy9PbahNMZC8tVa6Un5idq21UbH6O169Ys5sX+XVWh3AfUqch6SKDTrifrKaYszRNxttjHUbmFrK9ojetrgf+O/G+Df78F/gQdG1R0GDx+aAAAAABJRU5ErkJggg==)
    }
}
</pre></code>
</details>

**Comment by cocoelacanth** [comment]
Sorry, didn't see this until just now!

Thanks for the tip about the images. I moved them to GitHub a few months ago as it's much more reliable than using some random image host, but data URLs would (as you said) make everything more decentralized and improve speed. I think I'll look into moving those over.

As for the fonts, they seem to work just fine on my end. I'm not entirely sure what could be causing this— if the fonts are problematic I might have to remove them.

**Comment by cocoelacanth** [comment]
I've just released v13, which implements data URLs for images and adds an option to disable the Droid Sans font if it's causing issues. I'll mark this as complete for the time being.

**Comment by Commenter25** [comment]
No worries, glad to see the updates! Nothing was necessarily broken about the font, it just was blocked from loading. Interestingly, it's working for me now as well. Perhaps WinWorld changed something, or maybe I had a weird browser setup at the time. Who knows. Should be fine either way ^^
